### ISSUE TITLE
TODO

### ISSUE THREAD

**Issue by RiturajGupta21** [Diksha566/proj1#1]
1. Add favicon to the page
2. Fix the screen scrolling issue
3. Make the page responsive for different devices
4. Proper alignment of elements in the navbar
5. New form design
6. Need a Better Frontend and Color Scheme [Reference](https://dribbble.com/tags/gym%20website)
7. Create and link more pages as per the navbar contents

**Comment by Diksha566** [comment]
Okay i get that.
Gonna fix them
